[addon]
name = "sql"
description = "SQL Warehouse connection and query API"
group = "backend"

[python.edits]
imports = [
    "from .sql import SqlDependency",
]
aliases = [
    "Sql: TypeAlias = SqlDependency",
]
