[addon]
name = "sql"
description = "SQL Warehouse connection and query API"
group = "backend"

[python.edits]
exports = [
    "from .sql import SqlDependency, SqlConfig, get_sql, get_sql_config",
]
imports = [
    "from .sql import get_sql",
    "from databricks.sdk.service.sql import StatementExecutionAPI",
]
aliases = [
    "Sql: TypeAlias = Annotated[StatementExecutionAPI, Depends(get_sql)]",
]
