[project]
name = "apx"
dynamic = ["version"]
description = "Quickstarter for a Python + React project"
readme = "README.md"
authors = [
    { name = "renardeinside", email = "polarpersonal@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.119.0",
    "jinja2>=3.1.6",
    "typer>=0.19.2",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
format-jinja = "{{version}}"

[dependency-groups]
dev = [
    "fastapi>=0.119.0",
]

[project.scripts]
apx = "apx.__main__:app"

[tool.hatch.build.hooks.version]
path = "src/apx/_version.py"
template = '''
version = "{version}"
'''
