import json
import sys
from importlib import import_module
from pathlib import Path

from fastapi import FastAPI

from apx._core import generate_openapi, run_cli


def test_generate_openapi_skips_orval_when_schema_unchanged(tmp_path: Path) -> None:
    app_slug = "test_app"
    app_module = "test_app.backend.app:app"
    project_root = tmp_path
    src_dir = project_root / "src"
    backend_dir = src_dir / app_slug / "backend"
    backend_dir.mkdir(parents=True)
    (src_dir / app_slug / "__init__.py").write_text("")
    (backend_dir / "__init__.py").write_text("")
    (backend_dir / "app.py").write_text(
        "\n".join(
            [
                "from fastapi import FastAPI",
                "",
                "app = FastAPI()",
                "",
                "@app.get('/ping')",
                "def ping():",
                "    return {'status': 'ok'}",
                "",
            ]
        )
    )

    pyproject = "\n".join(
        [
            "[tool.apx.metadata]",
            'app-name = "Test App"',
            f'app-module = "{app_module}"',
            f'app-slug = "{app_slug}"',
            'api-prefix = "/api"',
            'metadata-path = "src/test_app/backend/_metadata.py"',
            "",
        ]
    )
    (project_root / "pyproject.toml").write_text(pyproject)

    sys.path.insert(0, str(project_root))
    sys.path.insert(0, str(project_root / "src"))
    try:
        module = import_module("test_app.backend.app")
        app = getattr(module, "app")  # pyright: ignore[reportAny]
        assert isinstance(app, FastAPI)
        expected_json = json.dumps(app.openapi(), indent=2)
    finally:
        sys.path.remove(str(project_root))

    apx_dir = project_root / ".apx"
    apx_dir.mkdir()
    (apx_dir / "openapi.json").write_text(expected_json)

    did_regenerate = generate_openapi(project_root, False)

    assert did_regenerate is False
    assert (apx_dir / "openapi.json").read_text() == expected_json
    assert (apx_dir / "orval.config.ts").exists()


def test_generate_openapi_with_rich_operations(e2e_init: Path) -> None:
    """Test OpenAPI generation with a rich set of CRUD operations."""
    project_root = e2e_init
    src_dir = project_root / "src"
    # The app is initialized with name "test-app" which becomes slug "test_app"
    backend_dir = src_dir / "test_app" / "backend"

    # Create a backend router with rich REST operations
    router_code = """from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from .config import conf

api = APIRouter(prefix=conf.api_prefix)

class Item(BaseModel):
    id: int
    name: str
    description: str | None = None
    price: float

class ItemCreate(BaseModel):
    name: str
    description: str | None = None
    price: float

class ItemUpdate(BaseModel):
    name: str | None = None
    description: str | None = None
    price: float | None = None

# Mock database
items_db: dict[int, Item] = {}

@api.get('/items', response_model=list[Item], operation_id='listItems')
def list_items():
    '''List all items'''
    return list(items_db.values())

@api.get('/items/{item_id}', response_model=Item, operation_id='getItem')
def get_item(item_id: int):
    '''Get a specific item by ID'''
    if item_id not in items_db:
        raise HTTPException(status_code=404, detail='Item not found')
    return items_db[item_id]

@api.post('/items', response_model=Item, status_code=201, operation_id='createItem')
def create_item(item: ItemCreate):
    '''Create a new item'''
    item_id = len(items_db) + 1
    new_item = Item(id=item_id, **item.model_dump())
    items_db[item_id] = new_item
    return new_item

@api.put('/items/{item_id}', response_model=Item, operation_id='updateItem')
def update_item(item_id: int, item: ItemCreate):
    '''Replace an entire item'''
    if item_id not in items_db:
        raise HTTPException(status_code=404, detail='Item not found')
    updated_item = Item(id=item_id, **item.model_dump())
    items_db[item_id] = updated_item
    return updated_item

@api.patch('/items/{item_id}', response_model=Item, operation_id='partialUpdateItem')
def partial_update_item(item_id: int, item: ItemUpdate):
    '''Partially update an item'''
    if item_id not in items_db:
        raise HTTPException(status_code=404, detail='Item not found')
    stored_item = items_db[item_id]
    update_data = item.model_dump(exclude_unset=True)
    updated_item = stored_item.model_copy(update=update_data)
    items_db[item_id] = updated_item
    return updated_item

@api.delete('/items/{item_id}', status_code=204, operation_id='deleteItem')
def delete_item(item_id: int):
    '''Delete an item'''
    if item_id not in items_db:
        raise HTTPException(status_code=404, detail='Item not found')
    del items_db[item_id]
    return None
"""

    # Write the router code
    (backend_dir / "router.py").write_text(router_code)

    # Create the _version.py file that would normally be generated by hatch
    (src_dir / "test_app" / "_version.py").write_text('version = "0.0.0"\n')

    # Ensure .apx directory exists
    apx_dir = project_root / ".apx"
    apx_dir.mkdir(exist_ok=True)

    # Run the __generate_openapi CLI command
    exit_code = run_cli(
        [
            "apx",
            "__generate_openapi",
            "--app-dir",
            str(project_root),
            "--force",
        ]
    )

    print(f"\n__generate_openapi exit code: {exit_code}")

    # Read and print the generated OpenAPI schema
    openapi_json_path = apx_dir / "openapi.json"
    if openapi_json_path.exists():
        openapi_schema = json.loads(openapi_json_path.read_text())
        print("\n" + "=" * 80)
        print("Generated OpenAPI Schema:")
        print("=" * 80)
        print(json.dumps(openapi_schema, indent=2))
        print("=" * 80)
        print(f"\nNumber of paths: {len(openapi_schema.get('paths', {}))}")
        print(f"Paths: {list(openapi_schema.get('paths', {}).keys())}")

        # Print operations by method
        paths = openapi_schema.get("paths", {})
        operations = {"get": [], "post": [], "put": [], "patch": [], "delete": []}
        for path, methods in paths.items():
            for method in ["get", "post", "put", "patch", "delete"]:
                if method in methods:
                    operations[method].append(path)

        print(f"\nOperations by method:")
        for method, paths_list in operations.items():
            if paths_list:
                print(f"  {method.upper()}: {paths_list}")
    else:
        print("OpenAPI schema file not found!")

    # Print the generated api.ts file
    api_ts_path = src_dir / "test_app" / "ui" / "lib" / "api.ts"
    if api_ts_path.exists():
        print("\n" + "=" * 80)
        print("Generated api.ts:")
        print("=" * 80)
        print(api_ts_path.read_text())
        print("=" * 80)
    else:
        print(f"\napi.ts file not found at: {api_ts_path}")
