[addon]
name = "genie"
description = "Genie Space client"
group = "backend"

[python.edits]
exports = ["from .genie import GenieDependency, get_genie"]
imports = [
    "from .genie import get_genie",
    "from databricks.sdk.service.dashboards import GenieAPI",
]
aliases = ["GenieSpace: TypeAlias = Annotated[GenieAPI, Depends(get_genie)]"]
