[addon]
name = "serving-endpoint"
description = "Serving Endpoint client"
group = "backend"

[python.edits]
exports = ["from .serving import ServingDependency, get_serving_endpoint"]
imports = [
    "from .serving import get_serving_endpoint",
    "from databricks.sdk.service.serving import ServingEndpointsAPI",
]
aliases = ["ServingEndpoint: TypeAlias = Annotated[ServingEndpointsAPI, Depends(get_serving_endpoint)]"]
