from pathlib import Path

__version__: str

def run_cli(args: list[str]) -> int: ...
def get_bun_binary_path() -> Path: ...
def generate_openapi(project_root: Path) -> bool: ...
def get_dotenv_vars() -> dict[str, str]: ...
