from collections.abc import Generator
from pathlib import Path
from typing import Any

__version__: str

def run_cli(args: list[str]) -> int: ...
def generate_openapi(project_root: Path) -> bool: ...
def get_dotenv_vars() -> dict[str, str]: ...

# ── Exceptions ───────────────────────────────────────────────────────────

class NotFound(Exception):
    """Return a 404 Not Found response."""
    ...

class BadRequest(Exception):
    """Return a 400 Bad Request response."""
    ...

class Forbidden(Exception):
    """Return a 403 Forbidden response."""
    ...

# ── Scheduler core ──────────────────────────────────────────────────────

class ApxSchedulerCore:
    def __init__(self) -> None: ...
    def sleep(self, delay: float) -> Timer: ...
    def create_event(self) -> Event: ...
    def checkpoint(self) -> Future: ...
    def current_time(self) -> float: ...
    def current_token(self) -> ApxSchedulerCore: ...
    def cancelled_exception_class(self) -> type[BaseException]: ...
    def create_cancel_scope_state(
        self, deadline: float = ..., shield: bool = False
    ) -> CancelScopeState: ...
    def create_task_group_core(self) -> TaskGroupCore: ...
    def create_lock_primitive(self) -> Lock: ...
    def create_semaphore_primitive(self, permits: int) -> Semaphore: ...
    def run_sync_in_worker_thread(
        self, func: object, abandon_on_cancel: bool = False
    ) -> BlockingTask: ...

class CancelScopeState:
    deadline: float
    shield: bool
    @property
    def cancel_called(self) -> bool: ...
    cancelled_caught: bool
    host_task_state: object | None
    def cancel(self) -> None: ...
    def is_effectively_cancelled(self) -> bool: ...
    def current_time(self) -> float: ...

class TaskGroupCore:
    def child_spawned(self) -> None: ...
    def child_completed(self, exception: BaseException | None = None) -> None: ...
    def get_completion_future(self) -> Future | None: ...
    def get_exceptions(self) -> list[BaseException]: ...
    def has_pending(self) -> bool: ...
    def has_exceptions(self) -> bool: ...
    def resolve_if_empty(self) -> None: ...

class Event:
    def is_set(self) -> bool: ...
    def set(self) -> None: ...
    def wait(self) -> EventWaiter: ...

class EventWaiter:
    def __await__(self) -> Generator[Any, None, None]: ...

class Future:
    @property
    def done(self) -> bool: ...
    def __await__(self) -> Generator[Any, None, Any]: ...

class Timer:
    @property
    def done(self) -> bool: ...
    def __await__(self) -> Generator[Any, None, None]: ...

class BlockingTask:
    def __await__(self) -> Generator[Any, None, Any]: ...

class Lock:
    def acquire(self) -> LockGuardFuture: ...
    def locked(self) -> bool: ...

class LockGuardFuture:
    def __await__(self) -> Generator[Any, None, LockGuard]: ...

class LockGuard:
    def release(self) -> None: ...
    def __enter__(self) -> LockGuard: ...
    def __exit__(
        self,
        _exc_type: type[BaseException] | None = None,
        _exc_val: BaseException | None = None,
        _exc_tb: object | None = None,
    ) -> bool: ...

class Semaphore:
    def acquire(self) -> SemaphoreAcquire: ...
    def available_permits(self) -> int: ...

class SemaphoreAcquire:
    def __await__(self) -> Generator[Any, None, SemaphorePermit]: ...

class SemaphorePermit:
    def release(self) -> None: ...

class CancelToken:
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...
    def check(self) -> None: ...

# ── Telemetry ────────────────────────────────────────────────────────────

class SpanHandle:
    """OTEL span usable as sync/async context manager."""
    def __init__(
        self, name: str, attributes: dict[str, str] | None = None
    ) -> None: ...
    def __enter__(self) -> SpanHandle: ...
    def __exit__(
        self,
        _exc_type: type[BaseException] | None = None,
        _exc_val: BaseException | None = None,
        _exc_tb: object | None = None,
    ) -> bool: ...
    async def __aenter__(self) -> SpanHandle: ...
    async def __aexit__(
        self,
        _exc_type: type[BaseException] | None = None,
        _exc_val: BaseException | None = None,
        _exc_tb: object | None = None,
    ) -> bool: ...
    def add_event(
        self, name: str, attributes: dict[str, str] | None = None
    ) -> None: ...
    def set_attribute(self, key: str, value: str) -> None: ...

class RustCounter:
    """OTLP counter backed by Rust."""
    def inc(self, value: int = 1, labels: dict[str, str] | None = None) -> None: ...

class RustHistogram:
    """OTLP histogram backed by Rust."""
    def observe(self, value: float, labels: dict[str, str] | None = None) -> None: ...

class RustGauge:
    """OTLP gauge backed by Rust."""
    def set(self, value: float, labels: dict[str, str] | None = None) -> None: ...

def create_counter(
    name: str, description: str = "", unit: str = ""
) -> RustCounter: ...
def create_histogram(
    name: str, description: str = "", unit: str = ""
) -> RustHistogram: ...
def create_gauge(
    name: str, description: str = "", unit: str = ""
) -> RustGauge: ...
def _emit_log(level: int, message: str, logger_name: str) -> None: ...
